# Generated by Django 3.2.8 on 2024-10-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=100, verbose_name='Dia')),
                ('horas', models.CharField(max_length=100, verbose_name='Horas')),
                ('tipoContrato', models.CharField(max_length=100, verbose_name='TipoC')),
            ],
        ),
    ]
