# Generated by Django 3.2.8 on 2024-11-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
    ]
